TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.0
  max_vel_theta: 0.2
  min_vel_theta: -0.2
  min_in_place_vel_theta: 0.1   
  max_rotational_vel: 0.2
  min_in_place_rotational_vel: 0.2
  acc_lim_th: 1.5
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  holonomic_robot: false
  pdist_scale: 0.6
  gdist_scale: 0.8
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  escape_vel: -0.01
  dwa: true

DWAPlannerROS:
  acc_lim_x: 1.0
  acc_lim_theta: 3.0
  acc_lim_y: 0.0
  max_trans_vel: 0.2
  min_trans_vel: 0.1
  min_vel_x: 0.0
  max_vel_x: 0.3
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.7
  min_rot_vel: 0.3
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.1
  forward_point_distance: 0.5
  path_distance_bias: 32.0 
  goal_distance_bias: 24.0
  penalize_negative_x: true
  vtheta_samples: 20
  sim_time: 1.7
  stop_time_buffer: 0.1
  latch_xy_goal_tolerance: true
  cheat_factor: 2.0