obstacle_range: 5.0
raytrace_range: 3.0
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.6, 0.3], [0.7, 0.0],[0.6, -0.3]]
#robot_radius: 0.8
inflation_radius: 1.0


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, expected_update_rate: 7.0, data_type: LaserScan, topic: scan, marking: true, clearing: true}





