obstacle_range: 5.0
raytrace_range: 3.0
footprint: [[-0.4, -0.4], [-0.4, 0.4], [0.7, 0.4], [0.7, -0.4]]
#robot_radius: 0.8
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}





