obstacle_range: 8.0
raytrace_range: 10.0
footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.6, 0.5], [0.7, 0.0],[0.6, -0.5]]
#robot_radius: 0.8
inflation_radius: 1.0


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}





