global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  static_map: true
  transform_tolerance: 1.0

amcl:

  initial_pose_x: -10000.0
  initial_pose_y: -10000.0
