controller_frequency: 4..0
base_local_planner:  dwa_local_planner/DWAPlannerROS
#base_global_planner: astar_planner/AStarPlanner
#planner_frequency: 0.2
amcl:

  initial_pose_x: -10000.0
  initial_pose_y: -10000.0
